import '../models/product_model.dart';

class DummyData {
  static List<CategoryModel> categories = [
    CategoryModel(id: 'c1', name: 'Cotton', imageUrl: 'assets/images/cotton.jpg', productCount: 1240),
    CategoryModel(id: 'c2', name: 'Silk', imageUrl: 'assets/images/silk.jpg', productCount: 320),
    CategoryModel(id: 'c3', name: 'Denim', imageUrl: 'assets/images/denim.jpg', productCount: 850),
    CategoryModel(id: 'c4', name: 'Linen', imageUrl: 'https://via.placeholder.com/150x150.png?text=Linen', productCount: 430),
    CategoryModel(id: 'c5', name: 'Polyester', imageUrl: 'https://via.placeholder.com/150x150.png?text=Polyester', productCount: 2100),
    CategoryModel(id: 'c6', name: 'Rayon', imageUrl: 'https://via.placeholder.com/150x150.png?text=Rayon', productCount: 560),
    CategoryModel(id: 'c7', name: 'Wool', imageUrl: 'https://via.placeholder.com/150x150.png?text=Wool', productCount: 190),
    CategoryModel(id: 'c8', name: 'Nylon', imageUrl: 'https://via.placeholder.com/150x150.png?text=Nylon', productCount: 780),
    CategoryModel(id: 'c9', name: 'Blended', imageUrl: 'https://via.placeholder.com/150x150.png?text=Blended', productCount: 1450),
    CategoryModel(id: 'c10', name: 'Printed', imageUrl: 'https://via.placeholder.com/150x150.png?text=Printed', productCount: 920),
  ];

  static List<ProductModel> products = [
    ProductModel(
      id: 'p1',
      name: 'Cotton Premium 60s',
      category: 'Cotton',
      description: 'High-quality 60s cotton yarn fabric suitable for premium shirts.',
      price: 120.0,
      unit: 'Meter',
      imageUrl: 'assets/images/cotton.jpg',
      moq: 100,
      rating: 4.8,
      seller: 'Surat Textiles Hub',
      gsm: 120,
      color: 'White',
      inStock: true,
      isFeatured: true,
      isPopular: true,
    ),
    ProductModel(
      id: 'p2',
      name: 'Organic Cotton Fabric',
      category: 'Cotton',
      description: '100% organic cotton, eco-friendly and soft.',
      price: 150.0,
      unit: 'Meter',
      imageUrl: 'assets/images/cotton.jpg',
      moq: 50,
      rating: 4.6,
      seller: 'EcoWeave India',
      gsm: 140,
      color: 'Beige',
      inStock: true,
      isNewArrival: true,
    ),
    ProductModel(
      id: 'p3',
      name: 'Premium Denim 12 OZ',
      category: 'Denim',
      description: 'Heavyweight denim fabric for jeans and jackets.',
      price: 250.0,
      unit: 'Meter',
      imageUrl: 'assets/images/denim.jpg',
      moq: 200,
      rating: 4.9,
      seller: 'Ahmedabad Mills',
      gsm: 400,
      color: 'Blue',
      inStock: false,
      isFeatured: true,
    ),
    ProductModel(
      id: 'p4',
      name: 'Polyester Blend Fabric',
      category: 'Polyester',
      description: 'Durable polyester blend for activewear.',
      price: 80.0,
      unit: 'Meter',
      imageUrl: 'https://via.placeholder.com/300x300.png?text=Poly+Blend',
      moq: 500,
      rating: 4.2,
      seller: 'Global Synthetics',
      gsm: 180,
      color: 'Black',
      inStock: true,
      isPopular: true,
    ),
    ProductModel(
      id: 'p5',
      name: 'Silk Premium Fabric',
      category: 'Silk',
      description: 'Luxurious pure silk for ethnic wear.',
      price: 800.0,
      unit: 'Meter',
      imageUrl: 'assets/images/silk.jpg',
      moq: 20,
      rating: 5.0,
      seller: 'Mysore Silks Ltd.',
      gsm: 80,
      color: 'Red',
      inStock: true,
      isFeatured: true,
      isNewArrival: true,
    ),
    ProductModel(
      id: 'p6',
      name: 'Linen Natural Fabric',
      category: 'Linen',
      description: 'Breathable natural linen for summer clothing.',
      price: 300.0,
      unit: 'Meter',
      imageUrl: 'https://via.placeholder.com/300x300.png?text=Linen+Fabric',
      moq: 100,
      rating: 4.7,
      seller: 'Kochi Natural Weaves',
      gsm: 160,
      color: 'Off-White',
      inStock: true,
      isPopular: true,
    ),
    ProductModel(
      id: 'p7',
      name: 'Rayon Challis Print',
      category: 'Rayon',
      description: 'Soft and flowy rayon fabric with floral prints.',
      price: 110.0,
      unit: 'Meter',
      imageUrl: 'https://via.placeholder.com/300x300.png?text=Rayon+Print',
      moq: 150,
      rating: 4.4,
      seller: 'Surat Textiles Hub',
      gsm: 110,
      color: 'Multi',
      inStock: true,
      isNewArrival: true,
    ),
  ];
}
